export const dataExamples = {
  movies: {
    columns: ["title", "genre", "year", "rating", "director", "imdb_id"],
    samples: [
      {
        title: "The Shawshank Redemption",
        genre: "Drama",
        year: "1994",
        rating: "9.3",
        director: "Frank Darabont",
        imdb_id: "tt0111161",
      },
      {
        title: "The Godfather",
        genre: "Crime",
        year: "1972",
        rating: "9.2",
        director: "Francis Ford Coppola",
        imdb_id: "tt0068646",
      },
      {
        title: "The Dark Knight",
        genre: "Action",
        year: "2008",
        rating: "9.0",
        director: "Christopher Nolan",
        imdb_id: "tt0468569",
      },
      {
        title: "Pulp Fiction",
        genre: "Crime",
        year: "1994",
        rating: "8.9",
        director: "Quentin Tarantino",
        imdb_id: "tt0110912",
      },
      {
        title: "Forrest Gump",
        genre: "Drama",
        year: "1994",
        rating: "8.8",
        director: "Robert Zemeckis",
        imdb_id: "tt0109830",
      },
      {
        title: "Inception",
        genre: "Sci-Fi",
        year: "2010",
        rating: "8.8",
        director: "Christopher Nolan",
        imdb_id: "tt1375666",
      },
      {
        title: "The Matrix",
        genre: "Sci-Fi",
        year: "1999",
        rating: "8.7",
        director: "The Wachowskis",
        imdb_id: "tt0133093",
      },
      {
        title: "Goodfellas",
        genre: "Crime",
        year: "1990",
        rating: "8.7",
        director: "Martin Scorsese",
        imdb_id: "tt0099685",
      },
      {
        title: "Schindler's List",
        genre: "Drama",
        year: "1993",
        rating: "8.9",
        director: "Steven Spielberg",
        imdb_id: "tt0108052",
      },
      {
        title: "Fight Club",
        genre: "Drama",
        year: "1999",
        rating: "8.8",
        director: "David Fincher",
        imdb_id: "tt0137523",
      },
      {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        genre: "Fantasy",
        year: "2001",
        rating: "8.8",
        director: "Peter Jackson",
        imdb_id: "tt0120737",
      },
      {
        title: "Star Wars: Episode IV - A New Hope",
        genre: "Sci-Fi",
        year: "1977",
        rating: "8.6",
        director: "George Lucas",
        imdb_id: "tt0076759",
      },
      {
        title: "Casablanca",
        genre: "Romance",
        year: "1942",
        rating: "8.5",
        director: "Michael Curtiz",
        imdb_id: "tt0034583",
      },
      {
        title: "Citizen Kane",
        genre: "Drama",
        year: "1941",
        rating: "8.3",
        director: "Orson Welles",
        imdb_id: "tt0033467",
      },
      {
        title: "The Avengers",
        genre: "Action",
        year: "2012",
        rating: "8.0",
        director: "Joss Whedon",
        imdb_id: "tt0848228",
      },
      {
        title: "Titanic",
        genre: "Romance",
        year: "1997",
        rating: "7.8",
        director: "James Cameron",
        imdb_id: "tt0120338",
      },
      {
        title: "Jurassic Park",
        genre: "Adventure",
        year: "1993",
        rating: "8.1",
        director: "Steven Spielberg",
        imdb_id: "tt0107290",
      },
      {
        title: "Avatar",
        genre: "Sci-Fi",
        year: "2009",
        rating: "7.8",
        director: "James Cameron",
        imdb_id: "tt0499549",
      },
      {
        title: "The Silence of the Lambs",
        genre: "Thriller",
        year: "1991",
        rating: "8.6",
        director: "Jonathan Demme",
        imdb_id: "tt0102926",
      },
      {
        title: "Saving Private Ryan",
        genre: "War",
        year: "1998",
        rating: "8.6",
        director: "Steven Spielberg",
        imdb_id: "tt0120815",
      },
    ],
  },

  netflix_shows: {
    columns: ["title", "type", "genre", "release_year", "rating", "duration", "country"],
    samples: [
      {
        title: "Stranger Things",
        type: "TV Show",
        genre: "Sci-Fi",
        release_year: "2016",
        rating: "8.7",
        duration: "4 Seasons",
        country: "United States",
      },
      {
        title: "The Crown",
        type: "TV Show",
        genre: "Drama",
        release_year: "2016",
        rating: "8.7",
        duration: "6 Seasons",
        country: "United Kingdom",
      },
      {
        title: "Ozark",
        type: "TV Show",
        genre: "Crime",
        release_year: "2017",
        rating: "8.4",
        duration: "4 Seasons",
        country: "United States",
      },
      {
        title: "Money Heist",
        type: "TV Show",
        genre: "Crime",
        release_year: "2017",
        rating: "8.2",
        duration: "5 Seasons",
        country: "Spain",
      },
      {
        title: "The Witcher",
        type: "TV Show",
        genre: "Fantasy",
        release_year: "2019",
        rating: "8.2",
        duration: "3 Seasons",
        country: "United States",
      },
      {
        title: "Bridgerton",
        type: "TV Show",
        genre: "Romance",
        release_year: "2020",
        rating: "7.3",
        duration: "2 Seasons",
        country: "United States",
      },
      {
        title: "Squid Game",
        type: "TV Show",
        genre: "Thriller",
        release_year: "2021",
        rating: "8.0",
        duration: "1 Season",
        country: "South Korea",
      },
      {
        title: "Wednesday",
        type: "TV Show",
        genre: "Comedy",
        release_year: "2022",
        rating: "8.1",
        duration: "1 Season",
        country: "United States",
      },
      {
        title: "Bird Box",
        type: "Movie",
        genre: "Horror",
        release_year: "2018",
        rating: "6.6",
        duration: "124 min",
        country: "United States",
      },
      {
        title: "Extraction",
        type: "Movie",
        genre: "Action",
        release_year: "2020",
        rating: "6.7",
        duration: "116 min",
        country: "United States",
      },
      {
        title: "The Irishman",
        type: "Movie",
        genre: "Crime",
        release_year: "2019",
        rating: "7.8",
        duration: "209 min",
        country: "United States",
      },
      {
        title: "Roma",
        type: "Movie",
        genre: "Drama",
        release_year: "2018",
        rating: "7.7",
        duration: "135 min",
        country: "Mexico",
      },
      {
        title: "Marriage Story",
        type: "Movie",
        genre: "Drama",
        release_year: "2019",
        rating: "7.9",
        duration: "137 min",
        country: "United States",
      },
      {
        title: "The Trial of the Chicago 7",
        type: "Movie",
        genre: "Drama",
        release_year: "2020",
        rating: "7.7",
        duration: "129 min",
        country: "United States",
      },
      {
        title: "Don't Look Up",
        type: "Movie",
        genre: "Comedy",
        release_year: "2021",
        rating: "7.2",
        duration: "138 min",
        country: "United States",
      },
      {
        title: "Red Notice",
        type: "Movie",
        genre: "Action",
        release_year: "2021",
        rating: "6.3",
        duration: "118 min",
        country: "United States",
      },
      {
        title: "The Adam Project",
        type: "Movie",
        genre: "Sci-Fi",
        release_year: "2022",
        rating: "6.7",
        duration: "106 min",
        country: "United States",
      },
      {
        title: "Glass Onion",
        type: "Movie",
        genre: "Mystery",
        release_year: "2022",
        rating: "7.2",
        duration: "139 min",
        country: "United States",
      },
      {
        title: "All Quiet on the Western Front",
        type: "Movie",
        genre: "War",
        release_year: "2022",
        rating: "7.8",
        duration: "148 min",
        country: "Germany",
      },
      {
        title: "The Gray Man",
        type: "Movie",
        genre: "Action",
        release_year: "2022",
        rating: "6.5",
        duration: "129 min",
        country: "United States",
      },
    ],
  },

  companies: {
    columns: ["name", "industry", "revenue", "employees", "founded", "headquarters"],
    samples: [
      {
        name: "Apple Inc.",
        industry: "Technology",
        revenue: "$394.3B",
        employees: "164,000",
        founded: "1976",
        headquarters: "Cupertino, CA",
      },
      {
        name: "Microsoft",
        industry: "Technology",
        revenue: "$211.9B",
        employees: "221,000",
        founded: "1975",
        headquarters: "Redmond, WA",
      },
      {
        name: "Amazon",
        industry: "E-commerce",
        revenue: "$513.9B",
        employees: "1,541,000",
        founded: "1994",
        headquarters: "Seattle, WA",
      },
      {
        name: "Google (Alphabet)",
        industry: "Technology",
        revenue: "$307.4B",
        employees: "190,000",
        founded: "1998",
        headquarters: "Mountain View, CA",
      },
      {
        name: "Tesla",
        industry: "Automotive",
        revenue: "$96.8B",
        employees: "140,000",
        founded: "2003",
        headquarters: "Austin, TX",
      },
      {
        name: "Meta (Facebook)",
        industry: "Social Media",
        revenue: "$134.9B",
        employees: "87,000",
        founded: "2004",
        headquarters: "Menlo Park, CA",
      },
      {
        name: "Netflix",
        industry: "Entertainment",
        revenue: "$31.6B",
        employees: "13,000",
        founded: "1997",
        headquarters: "Los Gatos, CA",
      },
      {
        name: "Nike",
        industry: "Apparel",
        revenue: "$51.2B",
        employees: "83,700",
        founded: "1964",
        headquarters: "Beaverton, OR",
      },
      {
        name: "Coca-Cola",
        industry: "Beverages",
        revenue: "$43.0B",
        employees: "82,500",
        founded: "1886",
        headquarters: "Atlanta, GA",
      },
      {
        name: "McDonald's",
        industry: "Food Service",
        revenue: "$23.2B",
        employees: "200,000",
        founded: "1955",
        headquarters: "Chicago, IL",
      },
      {
        name: "Walmart",
        industry: "Retail",
        revenue: "$611.3B",
        employees: "2,100,000",
        founded: "1962",
        headquarters: "Bentonville, AR",
      },
      {
        name: "JPMorgan Chase",
        industry: "Banking",
        revenue: "$158.1B",
        employees: "293,723",
        founded: "1799",
        headquarters: "New York, NY",
      },
      {
        name: "Johnson & Johnson",
        industry: "Healthcare",
        revenue: "$94.9B",
        employees: "152,700",
        founded: "1886",
        headquarters: "New Brunswick, NJ",
      },
      {
        name: "Visa",
        industry: "Financial Services",
        revenue: "$29.3B",
        employees: "26,500",
        founded: "1958",
        headquarters: "San Francisco, CA",
      },
      {
        name: "Procter & Gamble",
        industry: "Consumer Goods",
        revenue: "$80.2B",
        employees: "106,000",
        founded: "1837",
        headquarters: "Cincinnati, OH",
      },
      {
        name: "Intel",
        industry: "Semiconductors",
        revenue: "$79.0B",
        employees: "131,900",
        founded: "1968",
        headquarters: "Santa Clara, CA",
      },
      {
        name: "Disney",
        industry: "Entertainment",
        revenue: "$82.7B",
        employees: "220,000",
        founded: "1923",
        headquarters: "Burbank, CA",
      },
      {
        name: "IBM",
        industry: "Technology",
        revenue: "$60.5B",
        employees: "282,100",
        founded: "1911",
        headquarters: "Armonk, NY",
      },
      {
        name: "Oracle",
        industry: "Software",
        revenue: "$50.0B",
        employees: "164,000",
        founded: "1977",
        headquarters: "Austin, TX",
      },
      {
        name: "Salesforce",
        industry: "Software",
        revenue: "$31.4B",
        employees: "79,390",
        founded: "1999",
        headquarters: "San Francisco, CA",
      },
    ],
  },
}

export function getDataExample(dataType: string, columns: string[], maxRows = 20) {
  const example = dataExamples[dataType]
  if (!example) return []

  return example.samples.slice(0, maxRows).map((item) => {
    const result = {}
    columns.forEach((col) => {
      // Find matching column by exact match or partial match
      const key = Object.keys(item).find(
        (k) =>
          k.toLowerCase() === col.toLowerCase() ||
          k.toLowerCase().includes(col.toLowerCase()) ||
          col.toLowerCase().includes(k.toLowerCase()),
      )
      result[col] = key ? item[key] : `${col}_${Math.floor(Math.random() * 1000)}`
    })
    return result
  })
}
